### ISSUE TITLE
Add phenotypes field to existing Gene query

### ISSUE THREAD

**Issue by ayaanqui** [dictyBase/dicty-graphql-schema#65]
https://github.com/dictyBase/genomepage/pull/825 will be adding a "Gene Phenotypes" tab in addition to the "Gene Ontology" tab, which will require either a modification to the existing `Gene` query ([gene.graphql](https://github.com/dictyBase/dicty-graphql-schema/blob/8699b0319f7fd873b094d21c398c92d6dd6a9fe2/src/queries/gene.graphql)) or add a new query that will support the required types, etc.

Assuming we modify the existing `Gene` query, this is the structure that I propose:
```graphql
query Gene($gene: String!) {
  gene(gene: $gene) {
    id
    name
    goas {...}
    phenotypes {
      characteristics
      phenotype {...}
      reference {
        author
        title
        name
        links {
          dictyBase
          pubMed
          fullText
        }
      }
    }
  }
}
```

As noted above, we could also create a completely new query that has the required fields for the phenotype tab to function properly.

**Comment by ayaanqui** [comment]
## TODO
These are some of the tasks to be done/ features that the new queries and types should have:
- [ ] Create new type inside [src/schema/gene.graphql](https://github.com/dictyBase/dicty-graphql-schema/blob/8699b0319f7fd873b094d21c398c92d6dd6a9fe2/src/schema/gene.graphql)
  - [ ] Extends strain
  - [ ] Phenotypes column
  - [ ] Reference column with `Publication` type (See [src/schema/publication.graphql](https://github.com/dictyBase/dicty-graphql-schema/blob/8699b0319f7fd873b094d21c398c92d6dd6a9fe2/src/schema/publication.graphql))
- [ ] Update [src/queries/gene.graphql](https://github.com/dictyBase/dicty-graphql-schema/blob/8699b0319f7fd873b094d21c398c92d6dd6a9fe2/src/queries/gene.graphql) to hold field for strains
- [ ] Update [src/schema/query.graphql](https://github.com/dictyBase/dicty-graphql-schema/blob/8699b0319f7fd873b094d21c398c92d6dd6a9fe2/src/schema/query.graphql)
